import { useState } from 'react';
import { ArrowRightLeft, Check, Copy, Download, FileCode2, ShieldCheck } from 'lucide-react';
import type { NormalizedContext, TransformationResult } from '../models/normalizedModel';
import { mapToHL7 } from '../services/hl7Mapper';
import { Alert, download, EmptyState, Flow } from './Shared';

export function HL7Preview({ context, result, onResult }: { context?: NormalizedContext; result?: TransformationResult; onResult: (r: TransformationResult) => void }) {
  const [confirmed, setConfirmed] = useState(false); const [copied, setCopied] = useState(false); const [copyError, setCopyError] = useState('');
  if (!context) return <section className="panel"><EmptyState title="Choisissez un rendez-vous" icon={<ArrowRightLeft size={28} />}>Sélectionnez un patient puis un rendez-vous dans la vue métier pour préparer sa représentation HL7 v2.</EmptyState></section>;
  async function copy() { try { await navigator.clipboard.writeText(result!.hl7Message); setCopied(true); setCopyError(''); setTimeout(() => setCopied(false), 2000); } catch { setCopyError('Le navigateur ne permet pas la copie. Utilisez le téléchargement du fichier HL7.'); } }
  return <><section className="panel conversion-setup"><div className="panel-heading"><div><h2>Préparer le message</h2><p>Appointment/{context.appointment.id} · {context.patient.display}</p></div><Flow /></div><div className="conversion-controls"><label>Événement métier<select value="S12" onChange={() => {}}><option value="S12">SIU · S12 — Notification de nouvelle réservation</option><option disabled>S13 — Replanification (hors MVP)</option><option disabled>S14 — Modification (hors MVP)</option><option disabled>S15 — Annulation (hors MVP)</option></select></label><button className="button primary" disabled={!confirmed} onClick={() => onResult(mapToHL7(context, { trigger: 'S12', confirmed }))}><ArrowRightLeft size={17} />Générer le message HL7</button></div><label className="checkbox-label"><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} /><span>Je confirme le scénario pédagogique de notification d’une nouvelle réservation.<small>Un état FHIR ne prouve pas un événement historique. Ce choix est enregistré dans l’audit.</small></span></label><div className="subtle-note"><ShieldCheck size={16} />Validation du profil pédagogique local v1.0.0. Aucune émission vers un système de santé.</div></section>
    {!result ? <section className="panel"><EmptyState title="Le message apparaîtra ici" icon={<FileCode2 size={29} />}>La génération contrôle les identifiants, le contexte patient et les dates avant d’appliquer les règles de mapping.</EmptyState></section> : <><section className="panel message-panel"><div className="panel-heading"><div><div className="eyebrow">REPRÉSENTATION CIBLE</div><h2>HL7 v2.5.1 <span className="muted">/ SIU_S12</span></h2></div><span className={`badge result-${result.status.toLowerCase()}`}>{result.status}</span></div>
      {result.status === 'FAILED' ? <Alert>{result.errors.map((error, i) => <div key={i}>{error}</div>)}<p>Aucun message n’a été produit.</p></Alert> : <><div className="code-toolbar"><span><span className="dot" />message.hl7 <small>UTF-8 · séparateur CR</small></span><div><button className="code-button" onClick={() => void copy()}>{copied ? <Check size={15} /> : <Copy size={15} />}{copied ? 'Copié' : 'Copier'}</button><button className="code-button" onClick={() => download(result.hl7Message, `medirdv-${result.audit.correlationId}.hl7`)}><Download size={15} />Télécharger</button></div></div><pre className="hl7-code" aria-label="Message HL7 généré">{result.hl7Message.split('\r').filter(Boolean).map((line, i) => <div key={i}><span className="line-number" aria-hidden="true">{String(i + 1).padStart(2, '0')}</span><b>{line.slice(0, 3)}</b>{line.slice(3).split('|').map((part, index) => <span key={index}>{index > 0 && <span className="pipe">|</span>}{part}</span>)}</div>)}</pre><div className="code-footer"><ShieldCheck size={15} />Structure contrôlée selon le profil local · {result.hl7Message.split('\r').filter(Boolean).length} segments</div></>}
      {copyError && <Alert>{copyError}</Alert>}
    </section><section className="panel audit-panel"><div className="panel-heading"><div><h2>Audit de la transformation</h2><p>Provenance, règles appliquées et pertes identifiées.</p></div><button className="button small" onClick={() => download(JSON.stringify(result.audit, null, 2), `audit-${result.audit.correlationId}.json`, 'application/json')}><Download size={15} />Exporter l’audit</button></div><dl className="audit-meta"><div><dt>Corrélation</dt><dd>{result.audit.correlationId}</dd></div><div><dt>Horodatage</dt><dd>{result.audit.timestamp}</dd></div><div><dt>Règles de mapping</dt><dd>{result.audit.mappingVersion}</dd></div><div><dt>Standards</dt><dd>FHIR {result.audit.fhirVersion} → HL7 {result.audit.hl7Version}</dd></div></dl>
      {!!result.warnings.length && <details className="warning-details" open><summary>{result.warnings.length} avertissement{result.warnings.length > 1 ? 's' : ''} · données absentes et pertes</summary><ul>{result.warnings.map((warning, i) => <li key={i}>{warning}</li>)}</ul></details>}
      {!!result.fields.length && <details className="trace-details"><summary>Provenance des {result.fields.length} champs produits</summary><div className="table-scroll"><table><thead><tr><th>CHAMP CIBLE</th><th>DONNÉE SOURCE / RÈGLE</th><th>VALEUR CIBLE</th></tr></thead><tbody>{result.fields.map((field, i) => <tr key={i}><td><code>{field.target}</code></td><td><code>{field.source}</code><small>{field.rule}</small></td><td><code>{field.value}</code></td></tr>)}</tbody></table></div></details>}
    </section></>}
  </>;
}
